trigger:
  - master

resources:
  repositories:
    - repository: templates
      type: git
      name: FoodRES/foodres-azure-shared-pipeline
      ref: refs/heads/master

variables:
- group: marketplace-variables

extends:
  template: vscode-extension-pipeline.yml@templates
  parameters:
    publishToMarketplace: $[eq(variables['Build.SourceBranch'], 'refs/heads/master')]